C:/Users/jonas/Documents/GitHub/RCD-Smart-Home-v-0.1/WiFi_Setup/wifi setup 2.c File Reference
#include <SoftwareSerial.h>
Functions
SoftwareSerial esp8266 (11, 12)
void setup ()
void wifi ()
void loop ()
Variables
int sensorPin = A0
Photoresistor Pin.
int sensorValue = 0
Storing Sensor Value.
int buttpin = 4
Button pin.
int buttonState
Buttonstate.
int pressed = 0
pressed state
int ledPin = 3
LEE pin.
String Wlan = `WebServer`
wifi name
String WlanP = `1234567890`
wifi password
String IP = `192.168.4.2`
ip address
String Port = `3030`
port
Function Documentation
SoftwareSerial esp8266 (11, 12)
Referenced by loop(), setup(), and wifi().
void loop ()
Wait for Server to get started
connect to server
reset buttonstate
read the value from the sensor
switches LED on or off depending on input from the server
Definition at line 63 of file wifi setup 2.c.
References buttonState, buttpin, esp8266(), IP, ledPin, Port, pressed, sensorPin, sensorValue, and wifi().
void setup ()
Setup
Setup 2
Definition at line 26 of file wifi setup 2.c.
References buttpin, esp8266(), ledPin, sensorPin, Wlan, and WlanP.
void wifi ()
wifi setup
Definition at line 56 of file wifi setup 2.c.
References esp8266().
Referenced by loop().
Variable Documentation
int buttonState
Buttonstate.
Definition at line 12 of file wifi setup 2.c.
Referenced by loop().
int buttpin = 4
Button pin.
Definition at line 10 of file wifi setup 2.c.
Referenced by loop(), and setup().
String IP = `192.168.4.2`
ip address
Definition at line 22 of file wifi setup 2.c.
Referenced by loop().
int ledPin = 3
LEE pin.
Definition at line 16 of file wifi setup 2.c.
Referenced by loop(), and setup().
String Port = `3030`
port
Definition at line 24 of file wifi setup 2.c.
Referenced by loop().
int pressed = 0
pressed state
Definition at line 14 of file wifi setup 2.c.
Referenced by loop().
int sensorPin = A0
Photoresistor Pin.
Definition at line 6 of file wifi setup 2.c.
Referenced by loop(), and setup().
int sensorValue = 0
Storing Sensor Value.
Definition at line 8 of file wifi setup 2.c.
Referenced by loop().
String Wlan = `WebServer`
wifi name
Definition at line 18 of file wifi setup 2.c.
Referenced by setup().
String WlanP = `1234567890`
wifi password
Definition at line 20 of file wifi setup 2.c.
Referenced by setup().